EMS/Controllers/EMSController.cs
using EMS.Data;
using EMS.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.ModelBinding;
using Microsoft.AspNetCore.Mvc.Rendering;
using OfficeOpenXml;
using System.Security.Cryptography;
using System.Security.Cryptography.X509Certificates;

namespace EMS.Controllers
{
    public class EMSController : Controller
    {
        private readonly ApplicationDbContext _db;

        public EMSController(ApplicationDbContext db)
        {
            _db = db;
        }
        public IActionResult Homepage(string searchInput = "", string filterDropdown = "", string filterStatus = "")
        {
            var model = GetEmployeeDetails(); // Retrieve the employee details from your data source

            if (!string.IsNullOrEmpty(searchInput))
            {
                searchInput = searchInput.ToLower(); // Convert search input to lowercase

                switch (filterDropdown)
                {
                    case "empno":
                        model = model.Where(x => x.Empno.ToLower().Contains(searchInput));
                        break;
                    case "name":
                        model = model.Where(x => x.Name.ToLower().Contains(searchInput));
                        break;
                    case "designation":
                        model = model.Where(x => x.Designation.ToLower().Contains(searchInput));
                        break;
                    case "email":
                        model = model.Where(x => x.Email.ToLower().Contains(searchInput));
                        break;
                    case "phonenumber":
                        model = model.Where(x => x.PhoneNumber.ToLower().Contains(searchInput));
                        break;
                }
            }
            ViewData["FilterDropdownOptions"] = new List<SelectListItem>
    {
        new SelectListItem { Value = "empno", Text = "Employee Number", Selected = filterDropdown == "empno" },
        new SelectListItem { Value = "name", Text = "Name", Selected = filterDropdown == "name" },
        new SelectListItem { Value = "designation", Text = "Designation", Selected = filterDropdown == "designation" },
        new SelectListItem { Value = "email", Text = "Email", Selected = filterDropdown == "email" },
        new SelectListItem { Value = "phonenumber", Text = "Phone Number", Selected = filterDropdown == "phonenumber" }
    };

            // Populate filter status options
            ViewData["FilterStatusOptions"] = new List<SelectListItem>
    {
        new SelectListItem { Value = "", Text = "All", Selected = filterStatus == "" },
        new SelectListItem { Value = "active", Text = "Active", Selected = filterStatus == "active" },
        new SelectListItem { Value = "inactive", Text = "Inactive", Selected = filterStatus == "inactive" }
    };

            if (!string.IsNullOrEmpty(filterStatus))
            {
                filterStatus = filterStatus.ToLower(); // Convert filter status to lowercase

                if (filterStatus == "active")
                {
                    model = model.Where(x => x.Status);
                }
                else if (filterStatus == "inactive")
                {
                    model = model.Where(x => !x.Status);
                }
            }
            List<DetailsModel> model1 = model.Where(row => row.Deleteflag == 0).ToList();
            var sno = 1;
            foreach (var employee in model1)
            {
                employee.Sno = sno++;
            }

            model1 = model1.OrderByDescending(e => e.UpdatedDate).ToList();
            return View(model1);
        }



        // GET: Create
        public IActionResult Create()
        {
            return View();
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create(DetailsModel obj)
        {
            var obj1 = _db.Details.FirstOrDefault(d => d.Email == obj.Email);
            if (obj1 != null)
            {
                TempData["Email"] = "Email already exist ";
            }
            var obj2 = _db.Details.FirstOrDefault(d => d.PhoneNumber == obj.PhoneNumber);
            if (obj2 != null)
            {
                TempData["PhoneNumber"] = "Phone Number already exist ";
            }
            if (obj1 == null && obj2 == null)
            {
                ModelState.Remove(nameof(obj.Address));
                obj.Address = obj.Address1 + " , " + obj.Address2 + " , " + obj.City + " , " + obj.Address1 + " , " + obj.pincode.ToString();

                if (ModelState.IsValid)
                {
                    _db.Details.Add(obj);
                    _db.SaveChanges();
                    return RedirectToAction("Homepage"); // Redirect to Homepage action
                }
            }
            return View(obj);
        }
        public IActionResult ViewDetails(int? id)
        {
            if (id != null)
            {
                var obj = _db.Details.FirstOrDefault(d => d.Id == id);
                if (obj != null)
                    return View(obj);
            }
            return View();
        }
        [HttpGet]
        public IActionResult Edit(int? id)
        {
            if (id != null)
            {
                var obj = _db.Details.Find(id);
                if (obj != null)
                    return View(obj);
            }
            return View();
        }
        public IActionResult Check()
        {
            return View();
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Check(DetailsModel obj1)
        {

            var obj = _db.Details.FirstOrDefault(d => d.Empno == obj1.Empno);

            if (obj != null)
            {
                if (obj.PhoneNumber == obj.PhoneNumber)
                    return RedirectToAction("ViewDetails", obj);
                else
                    TempData["Error"] = " Phone number doesn't match with given Employee Number";
            }
            else
            {
                TempData["Error"] = "Credentials do not match";
            }
            return View();
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Edit(DetailsModel obj)
        {
            var obj1 = _db.Details.FirstOrDefault(d => d.Email == obj.Email && d.Id != obj.Id);
            if (obj1 != null)
            {
                TempData["Email"] = "Email already exist ";
            }
            var obj2 = _db.Details.FirstOrDefault(d => d.PhoneNumber == obj.PhoneNumber && d.Id != obj.Id);
            if (obj2 != null)
            {
                TempData["PhoneNumber"] = "Phone Number already exist ";
            }
            if (obj1 == null && obj2 == null)
            {
                var obj3 = _db.Details.Find(obj.Id);
                obj.Address = obj.Address1 + " , " + obj.Address2 + " , " + obj.City + " , " + obj.Address1 + " , " + obj.pincode.ToString();
                obj3.UpdatedDate = DateTime.Now;
                obj3.Email = obj.Email;
                obj3.PhoneNumber = obj.PhoneNumber;
                obj3.Address1 = obj.Address1;
                obj3.Address = obj.Address;
                obj3.Address2 = obj.Address2;
                obj3.City = obj.City;
                obj3.State = obj.State;
                obj3.pincode = obj.pincode;

                _db.SaveChanges();
                return RedirectToAction("Homepage");
            }
            return View();
        }
        public IActionResult Delete(int? id)
        {
            var obj = _db.Details.Find(id);
            obj.Deleteflag = 1;
            _db.SaveChanges();
            return RedirectToAction("Homepage");
        }
        public IActionResult PermanentDelete(int? id)
        {
            var obj = _db.Details.Find(id);
            _db.Details.Remove(obj);
            _db.SaveChanges();
            return RedirectToAction("RecycleBin");
        }
        private IEnumerable<DetailsModel> GetEmployeeDetails()
        {
            var employeeDetails = _db.Details.ToList();
            var sno = 1;

            foreach (var employee in employeeDetails)
            {
                employee.Sno = sno++;
            }

            return employeeDetails.OrderByDescending(e => e.UpdatedDate);
        }
        public IActionResult EmailCheck(string Email, int? Id)
        {
            if (Id == null)
            {
                var data = _db.Details.Where(e => e.Email == Email).SingleOrDefault();
                if (data != null)
                {
                    return Json($"Email already exist !!!");
                }
                else
                {
                    return Json(true);
                }
            }
            else
            {
                var data = _db.Details.Where(e => e.Email == Email && e.Id != Id).SingleOrDefault();
                if (data != null)
                {
                    return Json($"Email already exist !!!");
                }
                else
                {
                    return Json(true);
                }
            }
        }
        public IActionResult PhoneNumberCheck(string PhoneNumber, int? Id)
        {
            if (Id == null)
            {
                var data = _db.Details.Where(e => e.PhoneNumber == PhoneNumber).SingleOrDefault();
                if (data != null)
                {
                    return Json($"Phone Number already exist !!!");
                }
                else
                {
                    return Json(true);
                }
            }
            else
            {
                var data = _db.Details.Where(e => e.PhoneNumber == PhoneNumber && e.Id != Id).SingleOrDefault();
                if (data != null)
                {
                    return Json($"Phone Number already exist !!!");
                }
                else
                {
                    return Json(true);

EMS/Views/EMS/Check.cshtml
@model EMS.Models.DetailsModel

@{
    ViewData["Title"] = "Check";
}

<h1>Check</h1>

<h4>DetailsModel</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Check">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Empno" class="control-label"></label>
                <input asp-for="Empno" class="form-control" />
                <span asp-validation-for="Empno" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="PhoneNumber" class="control-label"></label>
                <input asp-for="PhoneNumber" class="form-control" />
                <span asp-validation-for="PhoneNumber" class="text-danger"></span>
            </div><br />
            
            <div class="form-group">
                <input type="submit" value="Submit" class="btn btn-primary" />
                <a asp-controller="EMS" asp-action="Homepage" class="btn btn-secondary ml-10" style="width:150px">Back to list</a>
            </div>
        </form>
    </div>
</div>


@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

EMS/Views/EMS/Create.cshtml
@model EMS.Models.DetailsModel


@{
    ViewData["Title"] = "Create";
}
<h4>Employee Personal Information</h4>
<hr />

<form asp-action="Create">
    <div asp-validation-summary="ModelOnly" class="text-danger"></div>
    <div class="row">
        <div class="col-md-4">
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
        </div>
        <div class="col-md-4">
            <div class="form-group">
                <label asp-for="DOB" class="control-label"></label>
                <input asp-for="DOB" class="form-control" />
                <span asp-validation-for="DOB" class="text-danger"></span>
            </div>
        </div>
        <div class="col-md-4">
            <div class="form-group">
                <label asp-for="Gender" class="control-label"></label>
                <select asp-for="Gender" class="form-control">
                    <option disabled selected>--select--</option>
                    <option value="Male">Male</option>
                    <option value="Female">Female</option>
                </select>


                <span asp-validation-for="Gender" class="text-danger"></span>
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col-md-4">
            <div class="form-group">
                <label asp-for="Email" class="control-label"></label>
                <input asp-for="Email" id="Email" class="form-control" />
                <span asp-validation-for="Email" id="email-error" class="text-danger"></span>
                @if (!string.IsNullOrEmpty(Convert.ToString(TempData["PhoneNumber"])))
                {
                    <p style="color:red">@TempData["PhoneNumber"]</p>
                }
            </div>
        </div>
        <div class="col-md-4">
            <div class="form-group">
                <label asp-for="PhoneNumber" class="control-label"></label>
                <input asp-for="PhoneNumber" class="form-control" />
                <span asp-validation-for="PhoneNumber" class="text-danger"></span>
                @if (!string.IsNullOrEmpty(Convert.ToString(TempData["PhoneNumber"])))
                {
                    <p style="color:red">@TempData["PhoneNumber"]</p>
                }
            </div>
        </div>
        <div class="col-md-4">
            <div class="form-group">
                <label asp-for="Address1" class="control-label"></label>
                <input asp-for="Address1" class="form-control" />
                <span asp-validation-for="Address1" class="text-danger"></span>
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col-md-4">
            <div class="form-group">
                <label asp-for="Address2" class="control-label"></label>
                <input asp-for="Address2" class="form-control" />
                <span asp-validation-for="Address2" class="text-danger"></span>
            </div>
        </div>
        <div class="col-md-4">
            <div class="form-group">

                <label asp-for="City" class="control-label"></label>
                <input asp-for="City" class="form-control" />
                <span asp-validation-for="City" class="text-danger"></span>
            </div>
        </div>
        <div class="col-md-4">
            <div class="form-group">

                <label asp-for="State" class="control-label"></label>
                <!--- India states -->
                <select asp-for="State" class="form-control">
                    <option disabled selected>Select state</option>
                    <option value="AN">Andaman and Nicobar Islands</option>
                    <option value="AP">Andhra Pradesh</option>
                    <option value="AR">Arunachal Pradesh</option>
                    <option value="AS">Assam</option>
                    <option value="BR">Bihar</option>
                    <option value="CH">Chandigarh</option>
                    <option value="CT">Chhattisgarh</option>
                    <option value="DN">Dadra and Nagar Haveli</option>
                    <option value="DD">Daman and Diu</option>
                    <option value="DL">Delhi</option>
                    <option value="GA">Goa</option>
                    <option value="GJ">Gujarat</option>
                    <option value="HR">Haryana</option>
                    <option value="HP">Himachal Pradesh</option>
                    <option value="JK">Jammu and Kashmir</option>
                    <option value="JH">Jharkhand</option>
                    <option value="KA">Karnataka</option>
                    <option value="KL">Kerala</option>
                    <option value="LA">Ladakh</option>
                    <option value="LD">Lakshadweep</option>
                    <option value="MP">Madhya Pradesh</option>
                    <option value="MH">Maharashtra</option>
                    <option value="MN">Manipur</option>
                    <option value="ML">Meghalaya</option>
                    <option value="MZ">Mizoram</option>
                    <option value="NL">Nagaland</option>
                    <option value="OR">Odisha</option>
                    <option value="PY">Puducherry</option>
                    <option value="PB">Punjab</option>
                    <option value="RJ">Rajasthan</option>
                    <option value="SK">Sikkim</option>
                    <option value="TN">Tamil Nadu</option>
                    <option value="TG">Telangana</option>
                    <option value="TR">Tripura</option>
                    <option value="UP">Uttar Pradesh</option>
                    <option value="UT">Uttarakhand</option>
                    <option value="WB">West Bengal</option>
                </select>
                <span asp-validation-for="State" class="text-danger"></span>
            </div>

        </div>
        <div class="col-md-4">
            <div class="form-group">
                <label asp-for="pincode" class="control-label"></label>
                <input asp-for="pincode" type="text"class="form-control" />
                <span asp-validation-for="pincode" class="text-danger"></span>
            </div>
        </div>
    </div>
    <h4>Employee Office Details</h4>
    <div class="row">
        <div class="col-md-4">
            <div class="form-group">
                <label asp-for="Empno" class="control-label"></label>
                <input asp-for="Empno" class="form-control" />
                <span asp-validation-for="Empno" class="text-danger"></span>
            </div>
        </div>
        <div class="col-md-4">
            <div class="form-group">
                <label asp-for="Designation" class="control-label"></label>
                <input asp-for="Designation" class="form-control" />
                <span asp-validation-for="Designation" class="text-danger"></span>
            </div>
        </div>
        <div class="col-md-4">
            <div class="form-group">
                <label asp-for="DOJ" class="control-label"></label>
                <input asp-for="DOJ" class="form-control" />
                <span asp-validation-for="DOJ" class="text-danger"></span>
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col-md-4">
            <div class="mb-3">
                <label asp-for="Status"></label>
                <select asp-for="Status" class="form-control">
                    <option disabled selected>Select Status</option>
                    <option value="True">Active</option>
                    <option value="False">Inactive</option>
                </select>
                <span asp-validation-for="Status" class="text-danger"></span>
            </div>
        </div>
    </div><br />
    <div class="form-group">
        <input type="submit" value="Create" class="btn btn-primary" />
        <a asp-controller="EMS" asp-action="Homepage" class="btn btn-secondary ml-10" style="width:150px">Back to list</a>
    </div>
</form>

<script src="~/lib/jquery/dist/jquery.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
<script src="~/js/site.js" asp-append-version="true"></script>
<script src="~/lib/jquery-validation-unobtrusive/jquery.validate.unobtrusive.js"></script>
<script src="~/lib/jquery-validation-unobtrusive/jquery.validate.unobtrusive.min.js"></script>
<script src="~/lib/jquery-validation/dist/jquery.validate.min.js"></script>

@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
}

EMS/Views/EMS/Homepage.cshtml
@model IEnumerable<DetailsModel>
@using Azure;
@{
    ViewData["Title"] = "Homepage";
    var searchInput = Context.Request.Query["searchInput"].ToString();
}
@using (Html.BeginForm("Homepage", "EMS", FormMethod.Get))
{
    <div class="container p-3">
        <div class="row pt-4 ">
            <div class="col-6">
                <h3>Employee Details</h3><br />
            </div>
            <div class="col-6 text-end">
                <a asp-controller="EMS" asp-action="Create" class="btn btn-success">+ Create new user</a>
                <a asp-controller="EMS" asp-action="RecycleBin" class="btn btn-primary">Recycle Bin</a>
                <a asp-action="ExportToExcel" class="btn btn-primary">Export to Excel</a>
            </div>

            <div class="row">
                <div class="col-md-12">
                    <div class="input-group">
                        <div class="col-md-3" style="margin-right: 5px;">
                            <input type="text" name="searchInput" class="form-control" placeholder="Search..." value="@searchInput">
                        </div>
                        <div class="col-md-3" style="margin-right: 5px;">
                            <select name="filterDropdown" class="form-select">
                                @foreach (var option in (IEnumerable<SelectListItem>)ViewData["FilterDropdownOptions"])
                                {
                                    <option value="@option.Value" selected="@option.Selected">@option.Text</option>
                                }

                            </select>
                        </div>
                        <div class="col-md-3" style="margin-right: 5px;">
                            <select name="filterStatus" class="form-select">
                                @foreach (var option in (IEnumerable<SelectListItem>)ViewData["FilterStatusOptions"])
                                {
                                    <option value="@option.Value" selected="@option.Selected" )>@option.Text</option>
                                }
                            </select>
                        </div>
                        <div class="col-md-2">
                            <button type="submit" class="btn btn-primary">Search</button>
                            <button type="reset" class="btn btn-primary" onclick="resetForm()">Reset</button>
                        </div>
                    </div>
                </div>
            </div>

        </div>
    </div>

}

<div class="container p-3">
    <div class="row pt-4">
        <table class="table table-bordered table-striped" style="width:100%">
            <thead>
                <tr>
                    <th>S.No</th>
                    <th>Employee Number</th>
                    <th>Name</th>
                    <th>Designation</th>
                    <th>Updated Date</th>
                    <th>Email</th>
                    <th>Phone Number</th>
                    <th>Status</th>
                    <th>View</th>
                    <th>Edit</th>
                    <th>Delete</th>
                </tr>
            </thead>
            <tbody>
                @foreach (var obj in Model)
                {
                    <tr>
                        <td width="20%">@obj.Sno</td>
                        <td width="20%">@obj.Empno</td>
                        <td width="20%">@obj.Name</td>
                        <td width="20%">@obj.Designation</td>
                        <td width="20%">@obj.UpdatedDate</td>
                        <td width="20%">@obj.Email</td>
                        <td width="20%">@obj.PhoneNumber</td>
                        <td width="20%">@(obj.Status ? "Active" : "Inactive")</td>
                        <td>
                            <a asp-controller="EMS" asp-action="ViewDetails" asp-route-id="@obj.Id">
                                <button class="btn btn-primary">View Details</button>
                            </a>
                        </td>
                        <td>
                            <a asp-controller="EMS" asp-action="Edit" asp-route-id="@obj.Id">
                                <button class="btn btn-warning">Edit</button>
                            </a>
                        </td>
                        <td>
                            <a asp-controller="EMS" asp-action="Delete" asp-route-id="@obj.Id">
                                <button class="btn btn-danger">Delete</button>
                            </a>
                        </td>
                    </tr>
                }
            </tbody>
        </table>
        <br /><br />
    </div>
</div>
<script>
    function resetForm() {
        document.querySelector('form').reset();
        window.location.href = '/EMS/Homepage';
    }
</script>

EMS/Views/EMS/RecycleBin.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@model IEnumerable<DetailsModel>
@{
    ViewData["Title"] = "Bin";
}

<div class="container p-3">
    <div class="row pt-4">
        <table class="table table-bordered table-striped" style="width:100%">
            <thead>
                <tr>
                    <th>S.No</th>
                    <th>Employee Number</th>
                    <th>Name</th>
                    <th>Designation</th>
                    <th>Updated Date</th>
                    <th>Email</th>
                    <th>Phone Number</th>
                    <th>Status</th>
                    <th>Undo</th>
                    <th>Permanent Delete</th>
                </tr>
            </thead>
            <tbody>
                @foreach (var obj in Model)
                {
                    <tr>
                        <td width="20%">@obj.Sno</td>
                        <td width="20%">@obj.Empno</td>
                        <td width="20%">@obj.Name</td>
                        <td width="20%">@obj.Designation</td>
                        <td width="20%">@obj.UpdatedDate</td>
                        <td width="20%">@obj.Email</td>
                        <td width="20%">@obj.PhoneNumber</td>
                        <td width="20%">@(obj.Status ? "Active" : "Inactive")</td>
                        <td>
                            <a asp-controller="EMS" asp-action="Undo" asp-route-id="@obj.Id">
                                <button class="btn btn-warning">Undo</button>
                            </a>
                        </td>
                        <td>
                            <a asp-controller="EMS" asp-action="PermanentDelete" asp-route-id="@obj.Id">
                                <button class="btn btn-danger">Remove</button>
                            </a>
                        </td>
                    </tr>
                }
            </tbody>
        </table>
        <br /><br />
    </div>
</div>

<div>
    <a asp-action="Homepage"><button class="btn btn-primary">Back to List</button></a>
</div>

EMS/Views/EMS/ViewDetails.cshtml
@model EMS.Models.DetailsModel

@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
    ViewData["Title"] = "ViewDetails";
}
<div class="container p-3">
    <div class="row pt-4">
        <div class="col-6 text-end">
            <a asp-controller="EMS" asp-action="Edit" asp-route-id="@Model.Id" class="btn btn-primary">Edit</a>
        </div>


    </div>
    <br><br>
    <table class="table table-bordered table-striped" style="width:100%">
        <tbody>
            <tr>
                <td width="20%">
                    Name
                </td>
                <td width="20%">
                    @Model.Name
                </td>
            </tr>
            <tr>
                <td width="20%">
                    DOB
                </td>
                <td width="20%">
                    @Model.DOB
                </td>
            </tr>
            <tr>
                <td width="20%">
                    Gender
                </td>
                <td width="20%">
                    @Model.Gender
                </td>
            </tr>
            <tr>
                <td width="20%">
                    Email
                </td>
                <td width="20%">
                    @Model.Email
                </td>
            </tr>
            <tr>
                <td width="20%">
                    Address
                </td>
                <td width="20%">
                    @Model.Address
                </td>
            </tr>
            <tr>
                <td width="20%">
                    State
                </td>
                <td width="20%">
                    @Model.State
                </td>
            <tr>
                <td DetailsModel="20%">
                    Employee Number
                </td>
                <td width="20%">
                        @Model.Empno
                </td>
            </tr>
            <tr>
                <td DetailsModel="20%">
                    Designation
                </td>
                <td width="20%">
                        @Model.Designation
                </td>
            </tr>
            <tr>
                <td DetailsModel="20%">
                    Status
                </td>
                @if (Model.Status)
                {
                    <td width="20%">Active</td>
                }
                else
                {
                    <td width="20%">Inactive</td>
                }
                </tr>
            <tr>
                <td DetailsModel="20%">
                    Phone Number
                </td>
                <td width="20%">
                        @Model.PhoneNumber
                </td>
            </tr>
            <tr>
                <td DetailsModel="20%">
                    DOJ
                </td>
                <td width="20%">
                        @Model.DOJ
                </td>
            </tr>
            <tr>
                <td DetailsModel="20%">
                    Created Date
                </td>
                <td width="20%">
                        @Model.CreatedDate
                </td>
            </tr>
            <tr>
                <td DetailsModel="20%">
                    Updated Date
                </td>
                <td width="20%">
                        @Model.UpdatedDate
                </td>
            </tr>

        </tbody>
    </table>
</div>